# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [3]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [5]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [8]:
np.array(my_list)

array([1, 2, 3])

In [13]:
# matrix 3x3
matrix = [[1,2,3], [4,5,6], [7,8,9]]
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
# 2 dimensional array 
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [17]:
# create an array with values includes from 0 to 9 (10 is not included)
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [19]:
# One dimensional vector
np.zeros(3)

array([0., 0., 0.])

In [22]:
# matrix with 2 rows and 3 cols
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.ones(3)

array([1., 1., 1.])

In [26]:
# matrix with 3 rows and 3 cols with ones
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [29]:
# 2 dimensional
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [31]:
np.linspace(0,10,51)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. ])

## eye

Creates an identity matrix

In [32]:
# diagonal matrice
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [34]:
np.random.rand(2)

array([0.56054704, 0.57569177])

In [36]:
np.random.rand(3,3)

array([[0.59818087, 0.79624034, 0.92790864],
       [0.87740091, 0.50358911, 0.31979096],
       [0.49408495, 0.26282019, 0.20013553]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [40]:
np.random.randn(2)

array([2.41062285, 0.68515864])

In [41]:
np.random.randn(4,4)

array([[ 0.6100604 , -0.34648939,  0.77561035, -0.55784979],
       [-0.0459644 , -0.675363  , -0.46077239, -0.30140838],
       [-0.1376251 , -0.83078149,  0.5811318 , -1.09339193],
       [ 0.27191345,  0.10159763,  0.48464492,  1.20914161]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [43]:
np.random.randint(1,100)

52

In [44]:
np.random.randint(1,100, 6)

array([90, 30,  6, 34, 39, 57])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [45]:
arr = np.arange(25)

In [47]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [48]:
rand_arr = np.random.randint(0, 50, 10)

In [49]:
rand_arr

array([28, 19,  5, 31, 26, 20,  0,  9, 48,  2])

## Reshape
Returns an array containing the same data with a new shape.

In [51]:
# reshape an array requires that num cols * num rows = length array
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [53]:
rand_arr.max()

48

In [55]:
rand_arr.min()

0

In [57]:
# index position of the max value in the array
rand_arr.argmax()

8

In [58]:
rand_arr.argmin()

6

## Shape

Shape is an attribute that arrays have (not a method):

In [60]:
# array with 25 elements
arr.shape

(25,)

In [61]:
arr = arr.reshape(5,5)

In [62]:
arr.shape

(5, 5)

### dtype

You can also grab the data type of the object in the array:

In [63]:
arr.dtype

dtype('int32')